name: mechanism
version: '1.0-SNAPSHOT'
main: org.example.artyom.mechanism.Mechanism
api-version: '1.21'

commands:
  getgen:
    description: Выдает кастомный генератор
  givecell:
    description: Выдает аккумулятор
  getbarrier:
    description: Выдает барьер
  getcable:
    description: Выдает кабель
  getencoder:
    description: Выдает шифратор
  monitor:
    description: Выдает информацию о механизмах в памяти
